// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function LoadModel(arg1:string):Promise<string>;

export function StartRendering(arg1:string):Promise<void>;

export function StopRendering():Promise<void>;
