// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelInfo() {
  return window['go']['main']['App']['GetModelInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function SaveScreenshot(arg1) {
  return window['go']['main']['App']['SaveScreenshot'](arg1);
}

export function StartRendering(arg1) {
  return window['go']['main']['App']['StartRendering'](arg1);
}

export function StopRendering() {
  return window['go']['main']['App']['StopRendering']();
}
